# Generated by Django 5.0.3 on 2024-03-28 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_customer_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('MasterCard', 'Master Card'), ('VisaCard', 'Visa Card')], max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('PaymentWaiting', 'Waiting for COD'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], max_length=200, null=True)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('PickedUp', 'Picked Up'), ('OutForDelivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('name', models.ManyToManyField(to='myapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('MasterCard', 'Master Card'), ('VisaCard', 'Visa Card'), ('JBC', 'JBC')], max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('PaymentCash', 'Payment is Cash'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], max_length=200, null=True)),
                ('table_status', models.CharField(choices=[('Paid', 'Paid'), ('OnBooked', 'On Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('name', models.ManyToManyField(to='myapp.menu')),
            ],
        ),
    ]
