# Generated by Django 5.0.3 on 2024-03-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_menu_customer_date_created_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reservetable',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='reservetable',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='reservetable',
            name='total_price',
        ),
        migrations.DeleteModel(
            name='OrderDelivery',
        ),
    ]
