# Generated by Django 5.0.3 on 2024-03-30 09:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_customer_address_remove_customer_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetable',
            name='table_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='table_status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ExclusiveReserveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('table_status', models.CharField(choices=[('Reserved', 'Reserved for 3 hours'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('reservation_start_time', models.TimeField()),
                ('reservation_end_time', models.TimeField()),
                ('reservation_duration_hours', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
                ('name', models.ManyToManyField(to='myapp.menu')),
            ],
        ),
    ]
