# Generated by Django 5.0.3 on 2024-03-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='catetory',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_category',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
