# Generated by Django 5.0.3 on 2024-04-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_menu_catetory_menu_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
