# Generated by Django 5.0.3 on 2024-04-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menu_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='catetory',
            new_name='category',
        ),
    ]
