# Generated by Django 5.0.3 on 2024-04-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_catetory_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivereservetable',
            name='table_status',
            field=models.CharField(choices=[('Downpayment', 'Downpayment paid'), ('Reserved', 'Reserved for 3 hours'), ('Paid', 'Complete Paid'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
