# Generated by Django 5.0.3 on 2024-04-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusivereservetable',
            old_name='persons',
            new_name='party_size',
        ),
        migrations.RenameField(
            model_name='reservetable',
            old_name='persons',
            new_name='party_size',
        ),
    ]
