# Generated by Django 5.0.3 on 2024-04-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_persons_exclusivereservetable_party_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusivereservetable',
            old_name='name',
            new_name='dish_name',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='dish_name',
        ),
        migrations.RenameField(
            model_name='reservetable',
            old_name='name',
            new_name='dish_name',
        ),
    ]
