# Generated by Django 5.0.3 on 2024-04-09 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_name_exclusivereservetable_dish_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='exclusivereservetable',
            old_name='customer',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='reservetable',
            old_name='customer',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lastname',
        ),
    ]
