# Generated by Django 5.0.3 on 2024-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_firstname_customer_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetable',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
