# Generated by Django 5.0.3 on 2024-04-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_reservetable_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservetable',
            old_name='prize',
            new_name='total_price',
        ),
    ]
