# Generated by Django 5.0.3 on 2024-04-09 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_prize_reservetable_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetable',
            name='party_size',
        ),
        migrations.AddField(
            model_name='reservetable',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
