# Generated by Django 5.0.3 on 2024-04-09 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_reservetable_party_size_reservetable_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetable',
            name='capacity',
        ),
        migrations.AddField(
            model_name='reservetable',
            name='party_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='table_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
