# Generated by Django 5.0.3 on 2024-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_reservetable_capacity_reservetable_party_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservetable',
            name='table_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
