# Generated by Django 5.0.3 on 2024-04-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_reservetable_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivereservetable',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
