# Generated by Django 5.0.7 on 2024-07-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivereservetable',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='reservetable',
            name='fullname',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
