# Generated by Django 5.1 on 2024-09-30 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_exclusivereservetable_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetable',
            name='dish_name',
        ),
        migrations.CreateModel(
            name='ExclusiveReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('party_size', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('table_status', models.CharField(choices=[('Downpayment', 'Downpayment paid'), ('Reserved', 'Reserved for 3 hours'), ('Paid', 'Complete Paid'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('reservation_start_time', models.TimeField()),
                ('reservation_end_time', models.TimeField()),
                ('reservation_duration_hours', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('dish_name', models.ManyToManyField(to='myapp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='NormalReservationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('party_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('table_status', models.CharField(choices=[('Reserved', 'Reserved'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('dish_name', models.ManyToManyField(to='myapp.menu')),
            ],
        ),
        migrations.DeleteModel(
            name='ExclusiveReserveTable',
        ),
        migrations.DeleteModel(
            name='ReserveTable',
        ),
    ]
