# Generated by Django 5.1 on 2024-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_reservetable_dish_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivereservationtable',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='normalreservationtable',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
