# Generated by Django 5.1 on 2024-10-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_exclusivereservationtable_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalreservationtable',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
