# Generated by Django 5.1 on 2024-10-03 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_normalreservationtable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
