# Generated by Django 5.1 on 2024-10-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_normalreservationtable_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
