# Generated by Django 5.1 on 2024-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_normalreservationtable_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='table_status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=200),
        ),
    ]
