# Generated by Django 5.1 on 2024-10-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_normalreservationtable_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
