# Generated by Django 5.1 on 2024-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_normalreservationtable_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Downpayment', 'Downpayment paid'), ('Reserved', 'Reserved for 3 hours'), ('Paid', 'Complete Paid'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
