# Generated by Django 5.1 on 2024-10-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_exclusivereservationtable_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivereservationtable',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
