# Generated by Django 5.1 on 2024-10-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_exclusivereservationtable_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusivereservationtable',
            old_name='reservation_duration_hours',
            new_name='duration',
        ),
    ]
