# Generated by Django 5.1 on 2024-10-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_rename_reservation_duration_hours_exclusivereservationtable_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
