# Generated by Django 5.1 on 2024-10-06 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_exclusivereservationtable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivereservationtable',
            name='duration',
        ),
    ]
