# Generated by Django 5.1 on 2024-10-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_exclusivereservationtable_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusivereservationtable',
            old_name='dish_name',
            new_name='dish_name_exclusive',
        ),
    ]
