# Generated by Django 5.1 on 2024-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_dish_name_exclusivereservationtable_dish_name_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivereservationtable',
            name='date',
        ),
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='reservation_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='reservation_start_time',
            field=models.DateTimeField(),
        ),
    ]
