# Generated by Django 5.1 on 2024-10-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_remove_exclusivereservationtable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='reservation_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='reservation_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
