# Generated by Django 5.1 on 2024-10-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_exclusivereservationtable_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivereservationtable',
            name='reservation_end_time',
        ),
        migrations.RemoveField(
            model_name='exclusivereservationtable',
            name='reservation_start_time',
        ),
    ]
