# Generated by Django 5.1 on 2024-10-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_remove_exclusivereservationtable_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivereservationtable',
            name='reservation_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='exclusivereservationtable',
            name='reservation_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
