# Generated by Django 5.1 on 2024-10-06 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_exclusivereservationtable_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExclusiveReservationTable',
            new_name='ExclusiveReservationsTable',
        ),
    ]
