# Generated by Django 5.1 on 2024-10-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_rename_exclusivereservationtable_exclusivereservationstable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExclusiveReservationsTable',
            new_name='ExclusiveReservationTable',
        ),
    ]
