# Generated by Django 5.1 on 2024-10-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_rename_exclusivereservationstable_exclusivereservationtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Downpayment paid', 'Downpayment paid'), ('Reserved for 3 hours', 'Reserved for 3 hours'), ('Complete Payment', 'Complete Payment'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
