# Generated by Django 5.1 on 2024-10-09 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_exclusivereservationtable_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09XXXXXXXXX'. Up to 11 digits allowed.", regex='^(09|\\+639\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='normalreservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('Pending Confirmation', 'Pending confirmation'), ('In progress', 'In progress'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
