# Generated by Django 5.1 on 2024-10-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_alter_normalreservationtable_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sub_category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Beverage', 'Beverage')], default='None', max_length=200),
        ),
    ]
