# Generated by Django 5.1 on 2024-10-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_menu_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sub_category',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
