# Generated by Django 5.1 on 2024-10-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_menu_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalreservationtable',
            name='dish_name',
        ),
        migrations.CreateModel(
            name='NormalReservationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normalreservationtable')),
            ],
        ),
    ]
