# Generated by Django 5.1 on 2024-10-13 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_normalreservationtable_dish_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclusivereservationtable',
            name='dish_name_exclusive',
        ),
        migrations.CreateModel(
            name='ExclusiveOrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exclusivereservationtable')),
            ],
        ),
    ]
