# Generated by Django 5.1 on 2024-10-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_exclusivereservationtable_dish_name_exclusive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
