# Generated by Django 5.1 on 2024-10-14 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_alter_normalreservationtable_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExclusiveOrderDish',
            new_name='ExclusiveReservationOrder',
        ),
    ]
