# Generated by Django 5.1 on 2024-10-23 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_rename_exclusiveorderdish_exclusivereservationorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclusivereservationtable',
            name='party_size',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
