# Generated by Django 5.1.4 on 2025-01-22 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_exclusivereservationtable_party_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVerificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('party_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('reservation_form', models.JSONField(blank=True, null=True)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('admin_action', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=50, null=True)),
            ],
        ),
    ]
