# Generated by Django 5.1.4 on 2025-01-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_adminverificationtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminverificationtable',
            old_name='date',
            new_name='chatbot_date',
        ),
        migrations.RenameField(
            model_name='adminverificationtable',
            old_name='total_price',
            new_name='chatbot_total_price',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='admin_action',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='admin_reviewed',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='party_size',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='reservation_form',
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='actions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='chatbot_dishes',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='chatbot_fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='chatbot_party_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='chatbot_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='form_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='form_fullname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='form_party_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='form_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
