# Generated by Django 5.1.4 on 2025-01-24 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_rename_date_adminverificationtable_chatbot_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAdminVerificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.normalreservationtable')),
            ],
        ),
    ]
