# Generated by Django 5.1.4 on 2025-01-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_nadminverificationorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NAdminVerificationOrder',
            new_name='AdminVerificationOrder',
        ),
    ]
