# Generated by Django 5.1.4 on 2025-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_rename_nadminverificationorder_adminverificationorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminverificationtable',
            old_name='chatbot_date',
            new_name='date_chatbot',
        ),
        migrations.RenameField(
            model_name='adminverificationtable',
            old_name='form_date',
            new_name='date_form',
        ),
        migrations.RenameField(
            model_name='adminverificationtable',
            old_name='chatbot_total_price',
            new_name='total_price_chatbot',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='chatbot_dishes',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='chatbot_fullname',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='chatbot_party_size',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='chatbot_phone',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='form_fullname',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='form_party_size',
        ),
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='form_phone',
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='dishes_chatbot',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='fullname_chatbot',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='fullname_form',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='party_size_chatbot',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='party_size_form',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='phone_chatbot',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='phone_form',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('Pending Confirmation', 'Pending confirmation'), ('In progress', 'In progress'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
