# Generated by Django 5.1.4 on 2025-02-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_rename_chatbot_date_adminverificationtable_date_chatbot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminverificationorder',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.adminverificationtable'),
        ),
        migrations.DeleteModel(
            name='ExclusiveReservationOrder',
        ),
        migrations.DeleteModel(
            name='ExclusiveReservationTable',
        ),
    ]
