# Generated by Django 5.1.4 on 2025-03-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_adminverificationorder_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminverificationtable',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminverificationtable',
            name='fullname_chatbot',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adminverificationtable',
            name='fullname_form',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adminverificationtable',
            name='table_status',
            field=models.CharField(default='Pending Confirmation', max_length=50),
        ),
    ]
