# Generated by Django 5.1.4 on 2025-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_adminverificationtable_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminverificationtable',
            name='email_chatbot',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
