# Generated by Django 5.1.4 on 2025-03-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_adminverificationtable_email_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalreservationtable',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
