# Generated by Django 5.1.4 on 2025-03-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_normalreservationtable_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminverificationtable',
            name='table_status',
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='confirmed_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='dishes_form',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='email_form',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='total_price_form',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='normalreservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('In progress', 'In progress'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=200, null=True),
        ),
    ]
