# Generated by Django 5.1.4 on 2025-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_remove_adminverificationtable_table_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminverificationtable',
            name='confirm_token_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminverificationtable',
            name='confirmation_token_created',
            field=models.DateTimeField(null=True),
        ),
    ]
