# Generated by Django 5.1.4 on 2025-07-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_adminverificationtable_confirm_token_use_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminVerificationOrder',
        ),
        migrations.DeleteModel(
            name='AdminVerificationTable',
        ),
    ]
