# Generated by Django 5.1.4 on 2025-07-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_sessiondishhistory'),
    ]

    operations = [
    ]
