# Generated by Django 5.1.4 on 2025-08-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailableDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateField(null=True, unique=True)),
                ('end_datetime', models.DateField(null=True, unique=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UnavailableDate',
        ),
        migrations.AlterField(
            model_name='normalreservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('In progress', 'In progress'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=200, null=True),
        ),
    ]
