# Generated by Django 5.1.4 on 2025-08-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_unavailabledatetime_delete_unavailabledate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailabledatetime',
            old_name='end_datetime',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='unavailabledatetime',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='unavailabledatetime',
            name='time',
            field=models.TimeField(null=True, unique=True),
        ),
    ]
