# Generated by Django 5.1.4 on 2025-08-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_rename_end_datetime_unavailabledatetime_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unavailabledatetime',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='unavailabledatetime',
            name='start_time',
            field=models.TimeField(null=True, unique=True),
        ),
    ]
