# Generated by Django 5.1.4 on 2025-08-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_rename_time_unavailabledatetime_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalreservationtable',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
