# Generated by Django 5.1.4 on 2025-08-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_normalreservationtable_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalreservationtable',
            name='table_status',
            field=models.CharField(blank=True, choices=[('Reserved', 'Reserved'), ('In progress', 'In progress'), ('Paid', 'Paid'), ('Completed', 'Completed'), ('No Show', 'No Show'), ('Cancelled', 'Cancelled')], default='Reserved', max_length=200, null=True),
        ),
    ]
